export const QUERY_PRODUCT_ACTION = "QUERY_PRODUCT_ACTION";
export const QUERY_PRODUCT_FAILURE_ACTION = "QUERY_PRODUCT_FAILURE_ACTION";
export const QUERY_PRODUCT_LIST_SUCCESS_ACTION = "QUERY_PRODUCT_LIST_SUCCESS_ACTION";

export const QUERY_PRODUCT_IN_PROGRESS = "QUERY_PRODUCT_IN_PROGRESS";
export const QUERY_RPODUCT_SUCCESS = "QUERY_PRODUCT_SUCCESS";
export const QUERY_PRODUCT_IDLE = "QUERY_PRODUCT_IDLE";
export const QUERY_PRODUCT_FAILURE = "QUERY_PRODUCT_FAILURE";