export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = "LOGOUT";
export const SERVER_ADDRESS_CHANGE = "SERVER_ADDRESS_CHANGE";
export const USER_NAME_CHANGE = 'USER_NAME_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const SWITCH_AUTH_METHOD = 'SWITCH_AUTH_METHOD';
